name: strix
description: strix app

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^1.0.2
  # state management and saving
  get_it: ^7.2.0
  shared_preferences: ^2.0.8
  # database
  firebase_core: ^1.8.0
  cloud_firestore: ^2.5.4
  firebase_auth: ^3.1.4
  #firebase_analytics: ^7.0.1

  # media and animations
  video_player: ^2.2.5
  #flutter_ringtone_player: ^3.0.0 #warning: deprecated version of Android embedding
  photo_view: ^0.13.0
  carousel_slider: ^4.0.0
  url_launcher: ^6.0.12
  simple_animations: ^4.0.1
  #expandable: ^5.0.1

  wakelock: ^0.5.6 #0.5.0+2
  tuple: ^2.0.0

  # icons, fonts, etc.
  font_awesome_flutter: ^9.2.0

  # packages needed for map functionality
  flutter_map: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/profile_pictures/
    - assets/calls/
    - assets/data/images/
    - assets/data/messages/
    - assets/data/social/
    - assets/pictures/ # keep or rename for all app related assets?
    - assets/videos/ # background videos


    # map assets (tiles)

    #    - assets/map/10/163/
    #    - assets/map/11/326/
    #    - assets/map/11/327/
    - assets/map/12/652/
    - assets/map/12/653/
    - assets/map/12/654/
    - assets/map/12/655/
    - assets/map/12/656/
    - assets/map/13/1305/
    - assets/map/13/1306/
    - assets/map/13/1307/
    - assets/map/13/1308/
    - assets/map/13/1309/
    - assets/map/13/1310/
    - assets/map/13/1311/
    - assets/map/13/1312/
    - assets/map/13/1313/
    - assets/map/14/2611/
    - assets/map/14/2612/
    - assets/map/14/2613/
    - assets/map/14/2614/
    - assets/map/14/2615/
    - assets/map/14/2616/
    - assets/map/14/2617/
    - assets/map/14/2618/
    - assets/map/14/2619/
    - assets/map/14/2620/
    - assets/map/14/2621/
    - assets/map/14/2622/
    - assets/map/14/2623/
    - assets/map/14/2624/
    - assets/map/14/2625/
    - assets/map/14/2626/
    - assets/map/14/2627/
    - assets/map/15/5222/
    - assets/map/15/5223/
    - assets/map/15/5224/
    - assets/map/15/5225/
    - assets/map/15/5226/
    - assets/map/15/5227/
    - assets/map/15/5228/
    - assets/map/15/5229/
    - assets/map/15/5230/
    - assets/map/15/5231/
    - assets/map/15/5232/
    - assets/map/15/5233/
    - assets/map/15/5234/
    - assets/map/15/5235/
    - assets/map/15/5236/
    - assets/map/15/5237/
    - assets/map/15/5238/
    - assets/map/15/5239/
    - assets/map/15/5240/
    - assets/map/15/5241/
    - assets/map/15/5242/
    - assets/map/15/5243/
    - assets/map/15/5244/
    - assets/map/15/5245/
    - assets/map/15/5246/
    - assets/map/15/5247/
    - assets/map/15/5248/
    - assets/map/15/5249/
    - assets/map/15/5250/
    - assets/map/15/5251/
    - assets/map/15/5252/
    - assets/map/15/5253/
    - assets/map/15/5254/
    - assets/map/15/5255/
    - assets/map/16/10445/
    - assets/map/16/10446/
    - assets/map/16/10447/
    - assets/map/16/10448/
    - assets/map/16/10449/
    - assets/map/16/10450/
    - assets/map/16/10451/
    - assets/map/16/10452/
    - assets/map/16/10453/
    - assets/map/16/10454/
    - assets/map/16/10455/
    - assets/map/16/10456/
    - assets/map/16/10457/
    - assets/map/16/10458/
    - assets/map/16/10459/
    - assets/map/16/10460/
    - assets/map/16/10461/
    - assets/map/16/10462/
    - assets/map/16/10463/
    - assets/map/16/10464/
    - assets/map/16/10465/
    - assets/map/16/10466/
    - assets/map/16/10467/
    - assets/map/16/10468/
    - assets/map/16/10469/
    - assets/map/16/10470/
    - assets/map/16/10471/
    - assets/map/16/10472/
    - assets/map/16/10473/
    - assets/map/16/10474/
    - assets/map/16/10475/
    - assets/map/16/10476/
    - assets/map/16/10477/
    - assets/map/16/10478/
    - assets/map/16/10479/
    - assets/map/16/10480/
    - assets/map/16/10481/
    - assets/map/16/10482/
    - assets/map/16/10483/
    - assets/map/16/10484/
    - assets/map/16/10485/
    - assets/map/16/10486/
    - assets/map/16/10487/
    - assets/map/16/10488/
    - assets/map/16/10489/
    - assets/map/16/10490/
    - assets/map/16/10491/
    - assets/map/16/10492/
    - assets/map/16/10493/
    - assets/map/16/10494/
    - assets/map/16/10495/
    - assets/map/16/10496/
    - assets/map/16/10497/
    - assets/map/16/10498/
    - assets/map/16/10499/
    - assets/map/16/10500/
    - assets/map/16/10501/
    - assets/map/16/10502/
    - assets/map/16/10503/
    - assets/map/16/10504/
    - assets/map/16/10505/
    - assets/map/16/10506/
    - assets/map/16/10507/
    - assets/map/16/10508/
    - assets/map/16/10509/
    - assets/map/16/10510/
    - assets/map/16/10511/

      #    - assets/map/17/20926/
      #    - assets/map/17/20927/
      #    - assets/map/17/20928/
      #    - assets/map/17/20929/
      #    - assets/map/17/20930/
      #    - assets/map/17/20931/
      #    - assets/map/17/20932/
      #    - assets/map/17/20933/
      #    - assets/map/17/20934/
      #    - assets/map/17/20935/
      #    - assets/map/17/20936/
      #    - assets/map/17/20937/
      #    - assets/map/17/20938/
      #    - assets/map/17/20939/
      #    - assets/map/17/20940/
      #    - assets/map/17/20941/
      #    - assets/map/17/20942/
      #    - assets/map/17/20943/
      #    - assets/map/17/20944/
      #    - assets/map/17/20945/
      #    - assets/map/17/20946/
      #    - assets/map/17/20947/
      #    - assets/map/17/20948/
      #    - assets/map/17/20949/
      #    - assets/map/17/20950/
      #    - assets/map/17/20951/
      #    - assets/map/17/20952/
      #    - assets/map/17/20953/
      #    - assets/map/17/20954/
      #    - assets/map/17/20955/
      #    - assets/map/17/20956/
      #    - assets/map/17/20957/
      #    - assets/map/17/20958/
      #    - assets/map/17/20959/
      #    - assets/map/17/20960/
      #    - assets/map/17/20961/
      #    - assets/map/17/20962/
      #    - assets/map/17/20963/
      #    - assets/map/17/20964/
      #    - assets/map/17/20965/
      #    - assets/map/17/20966/
      #    - assets/map/17/20967/
      #    - assets/map/17/20968/
      #    - assets/map/17/20969/
      #    - assets/map/17/20970/
      #    - assets/map/17/20971/
      #    - assets/map/17/20972/
      #    - assets/map/17/20973/
      #    - assets/map/17/20974/
      #    - assets/map/17/20975/
      #    - assets/map/17/20976/
      #    - assets/map/17/20977/
      #    - assets/map/17/20978/
      #    - assets/map/17/20979/
      #    - assets/map/17/20980/
      #    - assets/map/17/20981/
      #    - assets/map/17/20982/
      #    - assets/map/17/20983/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Thin.ttf
          weight: 100
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
